### ISSUE TITLE
Epic: photo-line features

### ISSUE THREAD

**Issue by olecom** [olecom/mamba.js#4]
Цель первого скрипта - поиск девушек в фотолинейке. Что сейчас неудобно:
- [ ] 1) Видно только 10-12 фото в линейке (в зависимости от разрешения экрана), и нет возможности быстро пролистать всех, кто там был в течение дня. Сидеть же на мамбе целый день - неинтересно :)

Нужна возможность собирать всю линейку в течение дня, чтобы потом посмотреть всю "портянку" одним кликом. Хорошо бы при этом сразу настроить фильтры вывода: отфильтровывать оттуда мужиков, слайдер по возрасту (если указан), не показывать персонажей из блеклиста (см. дальше).

Также было бы круто вывод самой штатной фотолинейки модифицировать в соответствии с этим же фильтром.

- [ ] 2) В полной версии Мамбы показываются только фото, а подписи к ним - попапами. В мобильной версии сайта сделано удобнее - слева фото, справа подписи.

Вывод списка по п.1 лучше сделать как в мобильной версии. Интегрировать это в дизайн/верстку сайта, наверное, необязательно, можно просто сгенерировать и выкинуть отдельной страницей - как будет проще в реализации.

- [ ] 3) Очень много в фотолинейке ...титуток, на отсев которых уходит дикое количество времени.
Было бы круто ...титуток сразу как-то выделять фоном, чтобы не тратить на них время.

Пока что формализуемые методы "экспертной оценки" выработаны такие:
Ручной: те девушки, которые уже проверены и установлено, что это ...титутка (я заношу их в отдельную папку или в игнор, можно и как-то по-другому, как будет удобнее для скрипта). В "общей портянке" нужно добавить какую-то кнопку, чтобы одним кликом, прочитав текст и установив по тексту, что это ...титутка, занести ее в блэклист.

Экспертные. Возможно, комбинировать их и перемножать их весовые коэффициенты:
- Дата регистрации. Те, которые на сайте очень давно (смотрю по номеру анкеты). Чем раньше регистрация, тем больше вероятность, что ...титутка. То же самое относится к совсем свежим (сегодня-вчера) анкетам.
- Количество "подарков" в анкете. Если их 0...5 - ок.  5...10 - подозрительно. Больше 10 - плохо.
- Те, которые регулярно и периодически торчат в фотолинейке. Скажем, сколько-то показов за какой-то период (например, 20 в неделю)

Конечно, круто было бы сюда прикрутить что-то самообучающееся, но это уже ненужный, хоть и интересный высший пилотаж ИМХО :)))
